import type { ReportData } from '@/types/report'

export const mockReport: ReportData = {
  brand: 'Sample Report',
  pages: [
    {
      id: 'scope',
      sectionNumber: '01',
      sectionLabel: '보고 범위',
      title: '진행 과제 현황과\n후속 판단 지점을 분리해 보고합니다',
      subtitle: '오늘은 현재 진행 중인 과제의 현황과 데모를 중심으로 보고하고, 추가 요청 범위는 별도 검토 대상으로 정리합니다.',
      layoutType: 'scope',
      isMuted: true,
      blocks: [
        { id: 'scope-b0', type: 'card', meta: '오늘 보고', title: '진행 현황 및 결과', body: '현재까지의 실행 결과와 확인된 효과를 공유합니다.', emphasis: true, accent: true },
        { id: 'scope-b1', type: 'card', meta: '후속 검토', title: '확대 적용 범위', body: '추가 요청은 범위, 일정, 책임 기준을 분리해 검토합니다.' },
        { id: 'scope-b2', type: 'card', meta: '판단 지점', title: '다음 단계 추진 여부', body: '효과와 리스크를 기준으로 후속 추진 방향을 결정합니다.' },
      ],
    },
    {
      id: 'overview',
      sectionNumber: '02',
      sectionLabel: '개요',
      title: '세부 설명에 앞서,\n핵심 수치와 추진 방향만 먼저 봅니다',
      subtitle: '아래 수치는 프로젝트 1건 기준으로 산정한 예시값입니다.',
      layoutType: 'overview-kpi',
      isMuted: false,
      blocks: [
        { id: 'overview-b0', type: 'kpi', value: '42', meta: 'h', title: '작업시간 절감', body: '적용 구간 기준의 직접 절감 효과입니다.' },
        { id: 'overview-b1', type: 'kpi', value: '38', meta: '%', title: '개선 대상 절감률', body: '개선 대상 업무 기준으로 환산한 값입니다.', emphasis: true },
        { id: 'overview-b2', type: 'kpi', value: '12', meta: '%', title: '전체 기준 환산', body: '전체 업무량 기준의 보수적 환산값입니다.' },
      ],
    },
    {
      id: 'problem',
      sectionNumber: '03',
      sectionLabel: '문제 정의',
      title: '현재 문제는 업무량보다,\n다음 단계로 이어지지 않는 산출물 구조입니다',
      subtitle: '단계가 많다는 사실보다, 사람이 다시 해석해야 하는 구조가 병목을 만듭니다.',
      layoutType: 'problem-cards',
      isMuted: true,
      blocks: [
        { id: 'problem-b0', type: 'card', meta: 'Problem 01', title: '재해석이 필요한 중간 산출물', body: '중간 결과가 다음 단계의 입력값으로 그대로 이어지지 않아 사람이 다시 해석합니다.' },
        { id: 'problem-b1', type: 'card', meta: 'Problem 02', title: '업무 구조와 기준의 분리', body: '역할별 산출물과 기준이 분리되어 반복 작업과 재작업이 발생합니다.' },
        { id: 'problem-b2', type: 'card', meta: 'Problem 03', title: '데이터화되지 않은 지식', body: '가이드, 체크리스트, 노하우가 시스템이 읽을 수 있는 형태로 준비되어 있지 않습니다.' },
      ],
    },
    {
      id: 'timeline',
      sectionNumber: '04',
      sectionLabel: '추진 일정',
      title: '확정 일정과 검토 예정 일정을\n분리해 정리합니다',
      subtitle: '단계별 범위는 확정 후 즉시 업데이트합니다.',
      layoutType: 'timeline',
      isMuted: false,
      blocks: [
        { id: 'timeline-b0', type: 'timeline', meta: '1단계 · 6월', body: '현황 분석 및 입력 구조 정의. 기준 데이터 수집 범위 확정.' },
        { id: 'timeline-b1', type: 'timeline', meta: '2단계 · 7월', body: 'MVP 기능 구현 및 내부 검증. 반복 업무 초안 생성 자동화 적용.' },
        { id: 'timeline-b2', type: 'timeline', meta: '3단계 · 8월', body: '운영 적용 및 효과 측정. 산정 기준 문서화 및 피드백 반영.' },
        { id: 'timeline-b3', type: 'timeline', meta: '후속 검토', body: '확대 적용 범위 및 조직 R&R은 3단계 완료 후 별도 검토합니다.' },
      ],
    },
    {
      id: 'tobe',
      sectionNumber: '05',
      sectionLabel: '개선 방향',
      title: '단순 자동화가 아니라,\nWorkflow가 이어지는 구조로 바꿉니다',
      subtitle: '입력과 산출물이 연결되고, 사람의 판단과 시스템 실행 범위가 분리되도록 구성합니다.',
      layoutType: 'to-be-flow',
      isMuted: true,
      blocks: [
        { id: 'tobe-b0', type: 'flow', meta: '01', title: '입력 구조 정리', body: '업무 요청과 기준을 시스템이 읽을 수 있게 분리합니다.' },
        { id: 'tobe-b1', type: 'flow', meta: '02', title: '중간 산출물 생성', body: '검토 가능한 초안을 빠르게 확보합니다.' },
        { id: 'tobe-b2', type: 'flow', meta: '03', title: '검토·수정·확정', body: '현업 판단이 필요한 영역은 사람이 검증합니다.' },
        { id: 'tobe-callout', type: 'text', body: '이 구조가 작동하려면 기능 구현과 함께 기준, 데이터, 운영 방식이 함께 준비되어야 합니다.' },
      ],
    },
    {
      id: 'effect',
      sectionNumber: '06',
      sectionLabel: '기대효과',
      title: '직접 효과와 간접 효과를 분리해 설명합니다',
      subtitle: '단순 절감률뿐 아니라 후속 적용을 위한 조건과 판단 근거도 함께 제시합니다.',
      layoutType: 'effect-split',
      isMuted: false,
      blocks: [
        { id: 'effect-b0', type: 'card', meta: '직접 효과', title: '시간·리드타임·반복 업무 절감', body: '현재 적용 범위에서 바로 기대할 수 있는 효과입니다. 반드시 산정 기준을 함께 표시합니다.', emphasis: true, accent: true },
        { id: 'effect-b1', type: 'card', meta: '간접 효과', title: '후속 전개 조건 확보', body: '운영 기준, 데이터 구조, 표준화 방식 등 다음 단계 의사결정에 필요한 조건을 확보합니다.' },
      ],
    },
  ],
}
