export { ScopePageTemplate } from './ScopeSection'
export { OverviewKPIPageTemplate } from './OverviewSection'
export { ProblemCardsPageTemplate } from './ProblemSection'
export { TimelinePageTemplate } from './TimelineSection'
export { ToBeFlowPageTemplate } from './ToBeSection'
export { EffectSplitPageTemplate } from './EffectSection'
export { ActivityReductionPageTemplate } from './ActivityReductionSection'
export { AsIsToBePageTemplate } from './AsIsToBeSection'
